sonar.projectKey=PokeRixe-front
sonar.projectName=PokeRixe Front
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**
sonar.coverage.exclusions=\
  **/*.model.ts,\
  **/core/auth/auth.mock.interceptor.ts,\
  **/core/auth/auth.interceptor.ts,\
  **/core/auth/auth.resolver.ts,\
  **/core/interceptors/error.interceptor.ts,\
  **/core/fight/fight-ws.service.ts,\
  **/app.config.ts,\
  **/app.routes.ts,\
  **/app.ts,\
  **/environments/**,\
  **/shared/models/**,\
  **/core/models/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
