name: Build and Deploy Pokerixe Front

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    environment: pokerixe-front
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Login ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get version
        id: pkg
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Build & Push image
        run: |
          docker build -t ghcr.io/baptouk/pokerixe-front:latest .
          docker push ghcr.io/baptouk/pokerixe-front:latest

      - name: Déployer sur le serveur
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            docker pull ghcr.io/${{ github.repository_owner }}/pokerixe-front:latest &&
            cd ~/pokerixe/ &&
            docker compose down &&
            docker compose up -d
          "
          rm private_key
